### ISSUE TITLE
Removal of RDS Civ

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/cba-settings-lock#23]
https://www.carpenoctem.co/forums/page/2/m/26081621/viewthread/33435731-repository-size-effects-on-performance-mission-making/post/139446714#p139446714

Since we will remove RDS Civ from our repository the following cba setting will have to be removed as well.

`Achilles_var_rds_rus_civ = true;`

**Comment by freghar** [comment]
Note that this (and similar) issue will likely resolve itself when updating the CBA settings for the new modset (which is something we need to do anyway as some mods may have renamed / added / removed settings). These extra settings will then automatically disappear.

The settings update due to mod update is basically:
1. Import current settings while on the current modset, export them again (to double check), save as `before.txt`
2. Update modset, start the game with new mod versions
3. Import current (old) settings, export to `after.txt`
4. Compare `before.txt` and `after.txt`, adjust `after.txt` as needed, commit the difference to git

**Comment by freghar** [comment]
(More details on https://github.com/CntoDev/cba-settings-lock/wiki/Updating-settings-on-modset-update )
